package:
  name: borgbackup
  version: "1.0.11rc1"

source:
  path: ../../

#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - borgbackup = borgbackup:main
    #
    # Would create an entry point called borgbackup that calls borgbackup.main()

    - borg = borg.archiver:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - msgpack-python >=0.4.6

  run:
    - python
    - msgpack-python >=0.4.6

test:
  # Python imports
  imports:
    - borg
    - borg.testsuite

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - borg --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://borgbackup.readthedocs.io/
  license: BSD License
  summary: 'Deduplicated, encrypted, authenticated and compressed backups'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
